(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/users_shell
$ python manage.py makemigrations
No changes detected
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/users_shell
$ cd ..
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm
$ django-admin startproject dojos_and_ninjas_shell
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm
$ cd dojo_and_ninjas_shell
bash: cd: dojo_and_ninjas_shell: No such file or directory
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm
$ cd dojos_and_ninjas_shel
bash: cd: dojos_and_ninjas_shel: No such file or directory
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm
$ cd dojos_and_ninjas_shell
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py startapp shell_app
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ code .
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 361, in execute
    self.check()
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\resolvers.py", line 571, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Mei\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_orm\dojos_and_ninjas_shell\dojos_and_ninjas_shell\urls.py", line 19, in <module>
    path('', include('shell_app.urls')),
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Mei\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'shell_app.urls'
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 361, in execute
    self.check()
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\resolvers.py", line 571, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Mei\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_orm\dojos_and_ninjas_shell\dojos_and_ninjas_shell\urls.py", line 19, in <module>
    path('', include('shell_app.urls')),
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Mei\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'shell_app.urls'
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 361, in execute
    self.check()
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\resolvers.py", line 571, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Mei\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'shell_app.urls'
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ cd shell_app
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell/shell_app
$ ls -a
./   __init__.py   admin.py  migrations/  tests.py
../  __pycache__/  apps.py   models.py    views.py
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell/shell_app
$ touch urls.py
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell/shell_app
$ touch urls.py
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell/shell_app
$ ls -a
./   __init__.py   admin.py  migrations/  tests.py  views.py
../  __pycache__/  apps.py   models.py    urls.py
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell/shell_app
$ cd ..
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 361, in execute
    self.check()
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\resolvers.py", line 398, in check
    for pattern in self.url_patterns:
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\resolvers.py", line 571, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Mei\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_orm\dojos_and_ninjas_shell\dojos_and_ninjas_shell\urls.py", line 19, in <module>
    path('', include('shell_app.urls')),
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\Mei\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_orm\dojos_and_ninjas_shell\shell_app\urls.py", line 4, in <module>
    path('', views.index),
AttributeError: module 'shell_app.views' has no attribute 'index'
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
No changes detected
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying sessions.0001_initial... OK
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> exit ()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ touch queries.txt
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from dojos_and_ninjas_shell.models import *
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'dojos_and_ninjas_shell.models'
>>> exit ()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
Migrations for 'shell_app':
  shell_app\migrations\0001_initial.py
    - Create model Dojos
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shell_app
Running migrations:
  Applying shell_app.0001_initial... OK
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shell_app.models import Dojos
>>> Dojos.objects.all()
<QuerySet []>
>>> exit ()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
Migrations for 'shell_app':
  shell_app\migrations\0002_ninjas.py
    - Create model Ninjas
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shell_app
Running migrations:
  Applying shell_app.0002_ninjas... OK
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shell_app.models import Ninjas
>>> Ninjas.objects.all()
<QuerySet []>
>>> from shell_app.models import *
>>> Dojos.objects.all()
<QuerySet []>
>>> Dojos.objects.create(name="Dojo1", city="San Jose", state="CA")
<Dojos: Dojos object (1)>
>>> Dojos.objects.all()
<QuerySet [<Dojos: Dojos object (1)>]>
>>> Dojos.objects.all()
  File "<console>", line 1
    Dojos.objects.all()
    ^
SyntaxError: invalid syntax
>>> Dojos.objects.all()
<QuerySet [<Dojos: Dojos object (1)>]>
>>> Dojos.self
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: type object 'Dojos' has no attribute 'self'
>>> Dojos.objects.self
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Manager' object has no attribute 'self'
>>> Dojos.objects.first()
<Dojos: Dojos object (1)>
>>> Dojos.objects.first()
<Dojos: Dojos object (1)>
>>> exit ()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shell_app.models import *
>>> Ninjas.objects.first()
>>> Dojos.objects.first()
Name: Dojo1
>>> Dojos.objects.create(name="Dojo2", city="Seattle", state="WA")
Name: Dojo2
>>> Dojo.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> Dojos.objects.all()
<QuerySet [Name: Dojo1, Name: Dojo2]>
>>> Dojos.objects.create(name="Dojo3", city="Chicago", state="IL")
Name: Dojo3
>>> Dojos.objects.all()
<QuerySet [Name: Dojo1, Name: Dojo2, Name: Dojo3]>
>>> c = Dojos.objects.get(id=1)
>>> c.delete()
(1, {'shell_app.Dojos': 1})
>>> c = Dojos.objects.get(id=2, id=3)
  File "<console>", line 1
SyntaxError: keyword argument repeated
>>> c = Dojos.objects.get(id=2)
>>> c.delete()
(1, {'shell_app.Dojos': 1})
>>> c = Dojos.objects.get(id=3)
>>> c.delete()
(1, {'shell_app.Dojos': 1})
>>> Dojos.objects.create(name="Dojo1", city="San Jose", state="CA")
Name: Dojo1
>>> Dojos.objects.create(name="Dojo2", city="Seattle", state="WA")
Name: Dojo2
>>> Dojos.obejcts.create(name="Dojo3", city="Chicago", state="IL")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: type object 'Dojos' has no attribute 'obejcts'
>>>
  File "<console>", line 1

    ^
SyntaxError: invalid syntax
>>> Dojos.objects.create(name="Dojo3", city="Chicago", state="IL")
Name: Dojo3
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=1), first_name="Mei", last_name="Manzo", city="Santa Cruz")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\db\models\query.py", line 408, in get
    self.model._meta.object_name
shell_app.models.Dojos.DoesNotExist: Dojos matching query does not exist.
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=4), first_name="Mei", last_name="Manzo", city="Santa Cruz")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\db\models\query.py", line 420, in create
    obj = self.model(**kwargs)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\db\models\base.py", line 501, in __init__
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))
TypeError: Ninjas() got an unexpected keyword argument 'dojo'
>>> exit()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
You are trying to add a non-nullable field 'dojo' to ninjas without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
>>> olddojo
Invalid input: name 'olddojo' is not defined
>>> exit
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
Migrations for 'shell_app':
  shell_app\migrations\0003_ninjas_dojo.py
    - Add field dojo to ninjas
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shell_app
Running migrations:
  Applying shell_app.0003_ninjas_dojo... OK
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shell_app import *
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=4), first_name="Mei", last_name="Manzo", city="Felton")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Ninjas' is not defined
>>> from shell_app.models import *
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=4), first_name="Mei", last_name="Manzo", city="Felton")
<Ninjas: Ninjas object (1)>
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=4), first_name="Trident", last_name="Gumchewer", city="Santa Cruz")
<Ninjas: Ninjas object (2)>
>>> Ninjas.obejcts.create(dojo=Dojos.objects.get(id=4), first_name="Tea", last_name="Drinker", city="Santa Cruz")
  File "<console>", line 1
    Ninjas.obejcts.create(dojo=Dojos.objects.get(id=4), first_name="Tea", last_name="Drinker", city="Santa Cruz")
                                             ^
SyntaxError: invalid syntax
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=4), first_name="Tea", last_name="Drinker", city="Santa Cruz")
<Ninjas: Ninjas object (3)>
>>> Ninjas.objects.create(dojo=Dojo.objects.get(id=5), first_name="Seafoam", lastname= "Breaks", city="Seattle")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=5), first_name="Seafoam", last_name="Breaker", city="Seattle")
<Ninjas: Ninjas object (4)>
>>> Ninjas.objects.create(dojo.Dojos.objects.get(id=5), first_name="Hotdog", last_name="Eater", city="Seattle)
  File "<console>", line 1
    Ninjas.objects.create(dojo.Dojos.objects.get(id=5), first_name="Hotdog", last_name="Eater", city="Seattle)
                                                                                                             ^
SyntaxError: EOL while scanning string literal
>>> Ninjas.objects.create(dojo.Dojos.objects.get(id=5), first_name="Hotdog", last_name="Eater", city="Seattle)
  File "<console>", line 1
    Ninjas.objects.create(dojo.Dojos.objects.get(id=5), first_name="Hotdog", last_name="Eater", city="Seattle)
                                                                                                             ^
SyntaxError: EOL while scanning string literal
>>> Ninjas.objects.create(dojo.Dojos.objects.get(id=5), first_name="Hotdog", last_name="Eater", city="Seattle")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'dojo' is not defined
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=5), first_name="HotDog", last_name="Eater", city="Seattle")
  File "<console>", line 1                                                     ast_name="Eater", city="Seattle")ojos.objects.get(id=5), first_name="Hot
                                                                                                                                                                                                                                                                                                                                                        ^
SyntaxError: invalid syntax
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=5), first_name="Hotdog", last_name="Eater", city="Seattle")
<Ninjas: Ninjas object (5)>
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=5), first_name="Candy", last_name="Eater", city="Seattle")
<Ninjas: Ninjas object (6)>
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=6), first_name="Pizza", last_name="Picker", city="Chicago")
<Ninjas: Ninjas object (7)>
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=6), first_name="Beer", last_name'"Drinker")
  File "<console>", line 1
    Ninjas.objects.create(dojo=Dojos.objects.get(id=6), first_name="Beer", last_name'"Drinker")
                                                                                              ^
SyntaxError: EOL while scanning string literal
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=6), first_name="Beer", last_name="Drinker")
  File "<console>", line 1
    Ninjas.objects reate(dojo=Dojos.objects.get(id=6), first_name="Beer", last_name="Drinker")
                  ^
SyntaxError: invalid syntax
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=6), first_name="Beer", last_name="Drinker", city="Chicago")
<Ninjas: Ninjas object (8)>
>>> Ninjas.objects.create(dojo=Dojos.objects.get(id=6), first_name="Pretzel", last_name="Chomper", city="Chicago")
<Ninjas: Ninjas object (9)>
>>> Dojos.Dojo1.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: type object 'Dojos' has no attribute 'Dojo1'
>>> Dojos.objects.filter(name="Dojo1")
<QuerySet [Name: Dojo1]>
>>> ninjas = Ninjas.objects.filter(dojo=Dojos.objects.get(id=4))
>>> print ninjas
  File "<console>", line 1
    print ninjas
               ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(ninjas)?
>>> print(ninjas)
<QuerySet [<Ninjas: Ninjas object (1)>, <Ninjas: Ninjas object (2)>, <Ninjas: Ninjas object (3)>]>
>>> exit()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
No changes detected
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> exit()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
No changes detected
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shell_app
Running migrations:
  No migrations to apply.
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shell_app.models import *
>>> ninjas = Ninjas.objects.filter(dojo=Dojos.objects.get(id=4))
>>> print(ninjas)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\db\models\query.py", line 253, in __repr__
    return '<%s %r>' % (self.__class__.__name__, data)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_orm\dojos_and_ninjas_shell\shell_app\models.py", line 24, in __repr__
    return "Name: {}".format(self.name)
AttributeError: 'Ninjas' object has no attribute 'name'
>>> print(ninjas)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_intro\my_environments\django\django\lib\site-packages\django\db\models\query.py", line 253, in __repr__
    return '<%s %r>' % (self.__class__.__name__, data)
  File "C:\Users\Mei\Desktop\Coding Dojo\python_stack\django\django_orm\dojos_and_ninjas_shell\shell_app\models.py", line 24, in __repr__
    return "Name: {} {}".format(self.first_name, self.last_name)
AttributeError: 'Ninjas' object has no attribute 'name'
>>> exit()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
No changes detected
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shell_app
Running migrations:
  No migrations to apply.
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shell_app.models import *
>>> ninjas = Ninjas.objects.filter(dojo=Dojo.objects.get(id=4))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojo' is not defined
>>> ninjas = Ninjas.objects.filter(dojo=Dojos.objects.get(id=4))
>>> print(ninjas)
<QuerySet [Name: Mei Manzo, Name: Trident Gumchewer, Name: Tea Drinker]>
>>> ninjas = Ninjas.objects.filter(dojo=Dojos.objects.get(id=5))
>>> print(ninjas)
<QuerySet [Name: Seafoam Breaker, Name: Hotdog Eater, Name: Candy Eater]>
>>> Ninjas.objects.last()
Name: Pretzel Chomper
>>> exit()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
No changes detected
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shell_app
Running migrations:
  No migrations to apply.
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shell
  File "<console>", line 1
    from shell
             ^
SyntaxError: invalid syntax
>>> from shell_app.models import *
>>> Ninjas.objects.last()
Dojo: Dojos object (6)
>>> exit()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
No changes detected
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shell_app
Running migrations:
  No migrations to apply.
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shell_app.models import *
>>> Ninjas.objects.last()
Dojo: Dojos object (6)
>>> exit()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
No changes detected
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shell_app
Running migrations:
  No migrations to apply.
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from shell_app.models import *
  File "<console>", line 1
    from shell_app.models import *
    ^
SyntaxError: invalid syntax
>>> from shell_app.models import *
>>> Ninjas.objects.last()
Name: Pretzel Chomper
>>> last_ninja = Ninjas.objects.last()
>>> last_ninja.dojo
Name: Dojo3
>>> exit()
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
You are trying to add a non-nullable field 'desc' to dojos without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: exit
Please select a valid option: 2
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py makemigrations
Migrations for 'shell_app':
  shell_app\migrations\0004_dojos_desc.py
    - Add field desc to dojos
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, shell_app
Running migrations:
  Applying shell_app.0004_dojos_desc... OK
(django)
Mei@Mei-PC MINGW64 ~/Desktop/Coding Dojo/python_stack/django/django_orm/dojos_and_ninjas_shell
$ python manage.py shell
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> Dojos.objects.create(name="Dojo4", city="San Francisco", state="CA", desc="New Dojo added")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Dojos' is not defined
>>> from shell_app.models import *
>>> Dojos.objects.create(name="Dojo4", city="San Francisco", state="CA", desc="New Dojo added")
Name: Dojo4
>>>
